name: Windows x86_64

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: windows-latest
    if: ${{ !contains(github.event.head_commit.message, 'NO_SW_CHANGE') && !contains(github.event.pull_request.body, 'NO_SW_CHANGE') }}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        release: false
        update: false
        install: >-
          base-devel
          git
          mingw-w64-x86_64-nodejs
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-curl
          mingw-w64-x86_64-freetype
          mingw-w64-x86_64-giflib
          mingw-w64-x86_64-libjpeg-turbo
          mingw-w64-x86_64-libpng
          mingw-w64-x86_64-libwebp
          mingw-w64-x86_64-pixman
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_image
          mingw-w64-x86_64-tinyxml2
          mingw-w64-x86_64-v8
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-libarchive
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Check for git tag
      id: check_tag
      shell: bash
      run: |
        if git describe --exact-match --tags 2>/dev/null; then
          echo "has_tag=true" >> $GITHUB_OUTPUT
        else
          echo "has_tag=false" >> $GITHUB_OUTPUT
        fi
    - name: Get short commit hash
      id: commit
      shell: bash
      run: |
        SHORT_HASH=$(git rev-parse --short HEAD)
        echo "short_hash=$SHORT_HASH" >> $GITHUB_OUTPUT
    - name: Update config.h with commit hash
      shell: bash
      run: |
        sed -i 's/#define COMMIT  "local build"/#define COMMIT  "${{ steps.commit.outputs.short_hash }}"/g' src/config.h
    - shell: msys2 {0}
      run: |
        mkdir build
        cd build
        if [ "${{ steps.check_tag.outputs.has_tag }}" = "true" ]; then
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DUSE_V8_SANDBOX=ON -DRELEASE_TAG=ON ..
        else
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DUSE_V8_SANDBOX=ON ..
        fi
        make -j 4
        cd ..
        rm build/bin/gen.exe
        node package_win.js build/bin/besprited.exe
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: besprited-development-windows-x86_64
        path: |
          build/bin/*
